/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as CustomerIndexRouteImport } from './routes/customer.index'
import { Route as CustomerNotificationsRouteImport } from './routes/customer.notifications'
import { Route as CustomerProfileRouteImport } from './routes/customer.profile'
import { Route as CustomerSubmitRouteImport } from './routes/customer.submit'
import { Route as EmployeeIndexRouteImport } from './routes/employee.index'
import { Route as EmployeeNotificationsRouteImport } from './routes/employee.notifications'
import { Route as EmployeeProfileRouteImport } from './routes/employee.profile'
import { Route as CustomerTicketsIndexRouteImport } from './routes/customer.tickets.index'
import { Route as CustomerTicketsIdRouteImport } from './routes/customer.tickets.$id'
import { Route as EmployeeTicketsIndexRouteImport } from './routes/employee.tickets.index'
import { Route as EmployeeTicketsIdRouteImport } from './routes/employee.tickets.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerNotificationsRoute = CustomerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerProfileRoute = CustomerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerSubmitRoute = CustomerSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => CustomerRoute,
} as any)
const EmployeeIndexRoute = EmployeeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeNotificationsRoute = EmployeeNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeProfileRoute = EmployeeProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => EmployeeRoute,
} as any)
const CustomerTicketsIndexRoute = CustomerTicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerTicketsIdRoute = CustomerTicketsIdRouteImport.update({
  id: '/tickets/$id',
  path: '/tickets/$id',
  getParentRoute: () => CustomerRoute,
} as any)
const EmployeeTicketsIndexRoute = EmployeeTicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeTicketsIdRoute = EmployeeTicketsIdRouteImport.update({
  id: '/tickets/$id',
  path: '/tickets/$id',
  getParentRoute: () => EmployeeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customer': typeof CustomerRouteWithChildren
  '/employee': typeof EmployeeRouteWithChildren
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/submit': typeof CustomerSubmitRoute
  '/employee/notifications': typeof EmployeeNotificationsRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/customer/': typeof CustomerIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/customer/tickets/$id': typeof CustomerTicketsIdRoute
  '/employee/tickets/$id': typeof EmployeeTicketsIdRoute
  '/customer/tickets/': typeof CustomerTicketsIndexRoute
  '/employee/tickets/': typeof EmployeeTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/submit': typeof CustomerSubmitRoute
  '/employee/notifications': typeof EmployeeNotificationsRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/customer': typeof CustomerIndexRoute
  '/employee': typeof EmployeeIndexRoute
  '/customer/tickets/$id': typeof CustomerTicketsIdRoute
  '/employee/tickets/$id': typeof EmployeeTicketsIdRoute
  '/customer/tickets': typeof CustomerTicketsIndexRoute
  '/employee/tickets': typeof EmployeeTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customer': typeof CustomerRouteWithChildren
  '/employee': typeof EmployeeRouteWithChildren
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/submit': typeof CustomerSubmitRoute
  '/employee/notifications': typeof EmployeeNotificationsRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/customer/': typeof CustomerIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/customer/tickets/$id': typeof CustomerTicketsIdRoute
  '/employee/tickets/$id': typeof EmployeeTicketsIdRoute
  '/customer/tickets/': typeof CustomerTicketsIndexRoute
  '/employee/tickets/': typeof EmployeeTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customer'
    | '/employee'
    | '/customer/notifications'
    | '/customer/profile'
    | '/customer/submit'
    | '/employee/notifications'
    | '/employee/profile'
    | '/customer/'
    | '/employee/'
    | '/customer/tickets/$id'
    | '/employee/tickets/$id'
    | '/customer/tickets/'
    | '/employee/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customer/notifications'
    | '/customer/profile'
    | '/customer/submit'
    | '/employee/notifications'
    | '/employee/profile'
    | '/customer'
    | '/employee'
    | '/customer/tickets/$id'
    | '/employee/tickets/$id'
    | '/customer/tickets'
    | '/employee/tickets'
  id:
    | '__root__'
    | '/'
    | '/customer'
    | '/employee'
    | '/customer/notifications'
    | '/customer/profile'
    | '/customer/submit'
    | '/employee/notifications'
    | '/employee/profile'
    | '/customer/'
    | '/employee/'
    | '/customer/tickets/$id'
    | '/employee/tickets/$id'
    | '/customer/tickets/'
    | '/employee/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomerRoute: typeof CustomerRouteWithChildren
  EmployeeRoute: typeof EmployeeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/': {
      id: '/customer/'
      path: '/'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/notifications': {
      id: '/customer/notifications'
      path: '/notifications'
      fullPath: '/customer/notifications'
      preLoaderRoute: typeof CustomerNotificationsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/profile': {
      id: '/customer/profile'
      path: '/profile'
      fullPath: '/customer/profile'
      preLoaderRoute: typeof CustomerProfileRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/submit': {
      id: '/customer/submit'
      path: '/submit'
      fullPath: '/customer/submit'
      preLoaderRoute: typeof CustomerSubmitRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/employee/': {
      id: '/employee/'
      path: '/'
      fullPath: '/employee/'
      preLoaderRoute: typeof EmployeeIndexRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/notifications': {
      id: '/employee/notifications'
      path: '/notifications'
      fullPath: '/employee/notifications'
      preLoaderRoute: typeof EmployeeNotificationsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/profile': {
      id: '/employee/profile'
      path: '/profile'
      fullPath: '/employee/profile'
      preLoaderRoute: typeof EmployeeProfileRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/customer/tickets/': {
      id: '/customer/tickets/'
      path: '/tickets'
      fullPath: '/customer/tickets/'
      preLoaderRoute: typeof CustomerTicketsIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/tickets/$id': {
      id: '/customer/tickets/$id'
      path: '/tickets/$id'
      fullPath: '/customer/tickets/$id'
      preLoaderRoute: typeof CustomerTicketsIdRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/employee/tickets/': {
      id: '/employee/tickets/'
      path: '/tickets'
      fullPath: '/employee/tickets/'
      preLoaderRoute: typeof EmployeeTicketsIndexRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/tickets/$id': {
      id: '/employee/tickets/$id'
      path: '/tickets/$id'
      fullPath: '/employee/tickets/$id'
      preLoaderRoute: typeof EmployeeTicketsIdRouteImport
      parentRoute: typeof EmployeeRoute
    }
  }
}

interface CustomerRouteChildren {
  CustomerNotificationsRoute: typeof CustomerNotificationsRoute
  CustomerProfileRoute: typeof CustomerProfileRoute
  CustomerSubmitRoute: typeof CustomerSubmitRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
  CustomerTicketsIdRoute: typeof CustomerTicketsIdRoute
  CustomerTicketsIndexRoute: typeof CustomerTicketsIndexRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerNotificationsRoute: CustomerNotificationsRoute,
  CustomerProfileRoute: CustomerProfileRoute,
  CustomerSubmitRoute: CustomerSubmitRoute,
  CustomerIndexRoute: CustomerIndexRoute,
  CustomerTicketsIdRoute: CustomerTicketsIdRoute,
  CustomerTicketsIndexRoute: CustomerTicketsIndexRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

interface EmployeeRouteChildren {
  EmployeeNotificationsRoute: typeof EmployeeNotificationsRoute
  EmployeeProfileRoute: typeof EmployeeProfileRoute
  EmployeeIndexRoute: typeof EmployeeIndexRoute
  EmployeeTicketsIdRoute: typeof EmployeeTicketsIdRoute
  EmployeeTicketsIndexRoute: typeof EmployeeTicketsIndexRoute
}

const EmployeeRouteChildren: EmployeeRouteChildren = {
  EmployeeNotificationsRoute: EmployeeNotificationsRoute,
  EmployeeProfileRoute: EmployeeProfileRoute,
  EmployeeIndexRoute: EmployeeIndexRoute,
  EmployeeTicketsIdRoute: EmployeeTicketsIdRoute,
  EmployeeTicketsIndexRoute: EmployeeTicketsIndexRoute,
}

const EmployeeRouteWithChildren = EmployeeRoute._addFileChildren(
  EmployeeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomerRoute: CustomerRouteWithChildren,
  EmployeeRoute: EmployeeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
